FROM golang:alpine

# Add build dependencies
# update-ca-certificates will show a warning, which is safe to ignore.
# https://github.com/gliderlabs/docker-alpine/issues/52
RUN apk update && \
    apk add --no-cache make upx ncurses ca-certificates && \
    update-ca-certificates

# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Move to working directory /build
WORKDIR /build

# Copy the code into the container
# We don't need to fetch dependencies since vendor directory is checked in
COPY . .

# Export necessary port
EXPOSE 8080

# For hot reloading
RUN go get github.com/githubnemo/CompileDaemon

# Command to run when starting the container
ENTRYPOINT CompileDaemon --build="make build.dev" --command=./bin/r2-d2
