// Code generated by go-swagger; DO NOT EDIT.

// Package restapi R2-D2
//
//  Facebook connector for C-3PO that manages & exposes Facebook group data
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
